### ISSUE TITLE
Bug: A couple files still don't open correctly

### ISSUE THREAD

**Issue by sevonj** [AlexCharlton/midi-msg#27]
Since 0.7.4, midi-msg can parse almost all of the ~1500 midi files I have on hand.

I bundled together the remaining failing files, except for the ones that I could tell were faulty for real.

[midimsg-sample-failparse.zip](https://github.com/user-attachments/files/18150786/midimsg-sample-failparse.zip)

**Comment by AlexCharlton** [comment]
Hello again @sevonj, and thanks for adding even more test cases!

So, all of these files actually contain invalid messages, and for all five files there are only two classes of errors: "byte overflows" (which is when the most significant bit of a byte is set when it shouldn't be) and empty sysexs (a sysex message that is nothing but an `F7` terminating byte). 

I realized, though, that we can take advantage of a property of MIDI files to continue to parse the file even though it has these invalid messages. Particularly for sysex messages, the message is prefixed with its length. This means that we can capture the set of bytes that didn't parse in an `Invalid` message (along with the error) and move on to the next event. So I've added this functionality in https://github.com/AlexCharlton/midi-msg/commit/ce4641c6a107561f586d03b1e3f5a320155a6d75

This change allows four of the five files you sent to be able to parse (albeit with some invalid messages). The remaining one – `dm_fever.mid` – also contains invalid _non-sysex_ messages. The first of these is a pitch wheel message featuring the bytes `E1, A6, 34`. The two bytes following the status byte are meant to be a 14 bit number, formed by concatenating the lower 7 bits of both bytes. The top bit of that second byte (`A6` = `1010 0110`) should not be set. I see many CC messages that also have similar "byte overflows" in this file too.

Now, it would be possible to take a similar approach that I just introduced for sysex messages, but for non-sysex message types. To do this, we'd need to parse the status byte of a failing message and then map that to how many bytes the message should occupy. With that length we could capture these Invalid messages and skip over them.

This is a bit more effort than I think I'd personally like to spend to be able to partially parse what is ultimately a non-conformant file. If you feel like submitting a PR that does this, I'd happily accept it, though.

Thanks again for the report!

**Comment by AlexCharlton** [comment]
Will publish a new release soon :)

**Comment by AlexCharlton** [comment]
v0.7.5 published

**Comment by sevonj** [comment]
Cool, thanks a lot for going through these!

I guess this also explains why I had these working before: only a bare minimum set of messages were parsed, and the many were just jumped over using the length, while byte overflows were not checked at all.

Working around invalid channel messages sounds doable, although I can also live without this rendition of the Dr. Mario theme. It might become more relevant later, with my plan to display detailed file info, like a breakdown into individual events.

That should be the last batch of failing samples I have. The ones I left out didn't have anything useful; it was either missing most of its contents, or a valid file, but wrapped into a RIFF chunk.

```
Files:
OK:       1424
ERR:      4
NoImp:    0
Skipped:  0
goodbye.
```

v0.7.5 does indeed work, and I see that the _not implemented_-events are also skipped. Thanks again.

**Comment by AlexCharlton** [comment]
Thank _you_ for all the test cases :)
