### ISSUE TITLE
Cannot release 0.4.0 until ascii gets a new version

### ISSUE THREAD

**Issue by AlexCharlton** [AlexCharlton/midi-msg#6]
Upon attempting to publish to crates.io: 
```
error: all dependencies must have a version specified when publishing.
dependency `ascii` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

**Comment by AlexCharlton** [comment]
@stuffmatic Turns out we're not quite out of the woods - crates doesn't let you include dependencies without explicit versions.

**Comment by AlexCharlton** [comment]
Blocked on https://github.com/tomprogrammer/rust-ascii/issues/79

**Comment by xkr47** [comment]
It seems @tomprogrammer (mainatiner of rust-ascii) has not had any activity on github whatsoever since Decmber 2020 so unless somebody hops in to maintain a fork, I don't think this is going to resolve..

**Comment by AlexCharlton** [comment]
Yeah, this is a pity. Will need to port that code over, I suppose

**Comment by AlexCharlton** [comment]
Oh hey, looks like you prompted Tom into a bit of action. Let's see if there's a release in the next little bit...

**Comment by xkr47** [comment]
Yeah I already tried replacing rust-ascii with `bstr` in my local checkout.. it worked fine, but slightly bigger crate as dep, so did not push it anywhere.. But now I see `bstr` has [added no_std support](https://github.com/BurntSushi/bstr/pull/83) as well, so don't know about the size hit anymore.

**Comment by AlexCharlton** [comment]
It only took me a year, but 0.4.0 is out!

Thanks for the bstr recommendation @xkr47, I did indeed replace rust-ascii with it, and I'd say the result is cleaner.
